/**
 * Public locked stubs for themed Pro section templates and page kits.
 * Real HTML lives in ~/sites/llmcss-pro/registry/{id}.json.
 */
import { lockedPreview } from './locked.mjs';

export const themedSectionTemplates = [
  {
    id: 'themed-nav-obsidian',
    name: 'Obsidian Product Nav',
    section: 'header',
    tier: 'pro',
    kind: 'themed',
    skin: 'obsidian',
    tags: ['themed', 'nav', 'obsidian', 'header'],
    placement: 'Top of Page (Above Fold)',
    guidance: {
      placement: 'Sticky header on an Obsidian-skinned marketing or product site.',
      bestUsedFor: 'SaaS and developer-tool landings that want a high-craft monochrome chrome.',
      avoidWhen: 'Warm editorial or colorful consumer brands; use the free wireframe nav instead.',
      pairsWith: ['themed-hero-obsidian', 'themed-footer-obsidian'],
    },
    html: lockedPreview('Obsidian Product Nav'),
  },
  {
    id: 'themed-hero-obsidian',
    name: 'Obsidian Split Hero',
    section: 'hero',
    tier: 'pro',
    kind: 'themed',
    skin: 'obsidian',
    tags: ['themed', 'hero', 'obsidian', 'split'],
    placement: 'Hero Section (Above Fold, immediately after Nav)',
    guidance: {
      placement: 'First content block under the nav. Occupies the primary viewport.',
      bestUsedFor: 'Product landings that lead with a real interface preview, not a gray wireframe.',
      avoidWhen: 'Text-only essays or login-only portals.',
      pairsWith: ['themed-nav-obsidian', 'themed-cta-executive'],
    },
    html: lockedPreview('Obsidian Split Hero'),
  },
  {
    id: 'themed-features-editorial',
    name: 'Editorial Feature Spread',
    section: 'features',
    tier: 'pro',
    kind: 'themed',
    skin: 'editorial',
    tags: ['themed', 'features', 'editorial', 'spread'],
    placement: 'Core Content (Mid-Funnel, below Hero)',
    guidance: {
      placement: 'After the hero. One dominant claim, two supporting columns, hairlines not nested cards.',
      bestUsedFor: 'Studios, publishers, and opinionated product pages.',
      avoidWhen: 'Dense SaaS feature matrices; use the free bento wireframe.',
      pairsWith: ['themed-cta-executive', 'themed-footer-obsidian'],
    },
    html: lockedPreview('Editorial Feature Spread'),
  },
  {
    id: 'themed-pricing-fintech',
    name: 'Fintech Two-Plan Pricing',
    section: 'pricing',
    tier: 'pro',
    kind: 'themed',
    skin: 'fintech',
    tags: ['themed', 'pricing', 'fintech', 'plans'],
    placement: 'Conversion Stage (Lower Funnel)',
    guidance: {
      placement: 'After features. Two plans with a clear primary, tabular prices, no four-up identical cards.',
      bestUsedFor: 'Usage-priced or seat-priced tools with a free and a paid tier.',
      avoidWhen: 'Enterprise comparison matrices; use pricing-matrix-pro (now free).',
      pairsWith: ['themed-cta-executive', 'themed-dash-header-fintech'],
    },
    html: lockedPreview('Fintech Two-Plan Pricing'),
  },
  {
    id: 'themed-cta-executive',
    name: 'Executive Closing Band',
    section: 'cta',
    tier: 'pro',
    kind: 'themed',
    skin: 'executive',
    tags: ['themed', 'cta', 'executive', 'band'],
    placement: 'Pre-Footer Conversion Anchor',
    guidance: {
      placement: 'Directly above the footer. Surface shift, one headline, one action.',
      bestUsedFor: 'B2B closers that should feel like a decision, not a newsletter capture.',
      avoidWhen: 'Pages that already end on a checkout form.',
      pairsWith: ['themed-hero-obsidian', 'themed-footer-obsidian'],
    },
    html: lockedPreview('Executive Closing Band'),
  },
  {
    id: 'themed-footer-obsidian',
    name: 'Obsidian Sitemap Footer',
    section: 'footer',
    tier: 'pro',
    kind: 'themed',
    skin: 'obsidian',
    tags: ['themed', 'footer', 'obsidian', 'sitemap'],
    placement: 'Bottom of Page',
    guidance: {
      placement: 'Last element in the document.',
      bestUsedFor: 'Marketing sites that need a compact four-column sitemap on Obsidian.',
      avoidWhen: 'App shells and focused checkout funnels.',
      pairsWith: ['themed-nav-obsidian', 'themed-cta-executive'],
    },
    html: lockedPreview('Obsidian Sitemap Footer'),
  },
  {
    id: 'themed-app-shell-obsidian',
    name: 'Obsidian App Shell',
    section: 'app-shell',
    tier: 'pro',
    kind: 'themed',
    skin: 'obsidian',
    tags: ['themed', 'app-shell', 'obsidian', 'dashboard'],
    placement: 'Application Viewport (Full Screen Root Layout)',
    guidance: {
      placement: 'Root layout for an authenticated product. Replaces marketing chrome.',
      bestUsedFor: 'Ops consoles and agent workspaces on Obsidian.',
      avoidWhen: 'Public marketing pages.',
      pairsWith: ['themed-dash-header-fintech', 'themed-obsidian-status-rail'],
    },
    html: lockedPreview('Obsidian App Shell'),
  },
  {
    id: 'themed-dash-header-fintech',
    name: 'Fintech Dashboard Header',
    section: 'app-shell',
    tier: 'pro',
    kind: 'themed',
    skin: 'fintech',
    tags: ['themed', 'dashboard', 'fintech', 'header'],
    placement: 'Top of an authenticated app page, under the product top bar.',
    guidance: {
      placement: 'Below app chrome. Title, one primary metric, one action. Do not restamp four KPI tiles.',
      bestUsedFor: 'Treasury, billing, and ledger overviews.',
      avoidWhen: 'Marketing heroes.',
      pairsWith: ['themed-app-shell-obsidian', 'themed-fintech-ledger-row'],
    },
    html: lockedPreview('Fintech Dashboard Header'),
  },
];

export const themedPageKits = [
  {
    id: 'kit-obsidian-saas',
    name: 'Obsidian SaaS Landing',
    description: 'Production landing: Obsidian nav and hero, editorial feature spread, fintech pricing, executive closer, Obsidian footer.',
    recommendedFor: 'Developer-tool and B2B SaaS launches that should look shipped, not wireframed.',
    tier: 'pro',
    kind: 'themed',
    skin: 'obsidian',
    sections: [
      'themed-nav-obsidian',
      'themed-hero-obsidian',
      'themed-features-editorial',
      'themed-pricing-fintech',
      'themed-cta-executive',
      'themed-footer-obsidian',
    ],
  },
  {
    id: 'kit-fintech-dashboard',
    name: 'Fintech Dashboard Kit',
    description: 'Authenticated console: Obsidian app shell plus a fintech dashboard header with a single dominant figure.',
    recommendedFor: 'Treasury, billing, and usage consoles.',
    tier: 'pro',
    kind: 'themed',
    skin: 'fintech',
    sections: ['themed-app-shell-obsidian', 'themed-dash-header-fintech'],
  },
];
