/**
 * LLMCSS utility matrix specification.
 *
 * Plain ESM data module. No TypeScript, no dependencies, no side effects, so
 * build-utilities.mjs, build-manifests.mjs, the CLI and the MCP server can all
 * import it without a compile step. Everything exported is JSON-serialisable
 * once the helpers at the top have run.
 *
 * Class names carry no namespace prefix (branch `unprefixed`). Custom
 * properties keep the --ai-* namespace.
 *
 * A family is the unit of generation, of documentation and of manifest
 * attribution. One family produces one contiguous block of CSS.
 *
 *   id            unique family id, also the emitted section comment
 *   family        the bucket reported in public/classes.json
 *   priority      P0 ships first, P1 second, P2 last; used by --check budgets
 *   tier          A full matrix, B breakpoints only, C base only
 *   states        names from stateSets, applied on top of the tier
 *   prefix        class = prefix + '-' + key, or key alone when prefix is null,
 *                 or prefix alone when key is ''
 *   props         CSS properties a string value is written to
 *   values        key -> string (written to every prop) or key -> object of
 *                 property/value pairs when the suffix needs its own shape
 *   variantValues 'all', or the subset of keys that gets variant copies
 *   selectorSuffix appended to the escaped class selector (space-y uses it)
 *   notes         reviewer-facing rationale
 */

/* -------------------------------------------------------------------------
   Helpers. These run once at import; the exported data is plain.
   ------------------------------------------------------------------------- */

const spaceToken = (k) => `var(--ai-space-${String(k).replace('.', '-')})`;
const negSpace = (k) => `calc(-1 * ${spaceToken(k)})`;
const map = (keys, fn) => Object.fromEntries(keys.map((k) => [String(k), fn(k)]));
const range = (a, b) => Array.from({ length: b - a + 1 }, (_, i) => a + i);

/* -------------------------------------------------------------------------
   Scales
   ------------------------------------------------------------------------- */

/** Full spacing scale. Every step exists as a --ai-space-* token. */
export const SPACE = [
  '0', 'px', '0.5', '1', '1.5', '2', '2.5', '3', '3.5', '4', '5', '6', '7', '8',
  '9', '10', '11', '12', '14', '16', '20', '24', '28', '32', '36', '40', '48',
  '56', '64', '72', '80', '96',
];

/** Side-specific spacing (pt, pr, ms, ...). Stops at 32; nothing needs pt-96. */
export const SPACE_SIDE = [
  '0', 'px', '0.5', '1', '1.5', '2', '2.5', '3', '3.5', '4', '5', '6', '7', '8',
  '10', '12', '14', '16', '20', '24', '32',
];

/** Negative spacing. Symmetric across every negative family. */
export const SPACE_NEG = ['px', '0.5', '1', '1.5', '2', '2.5', '3', '4', '5', '6', '8', '10', '12', '16', '20', '24'];

/**
 * The single responsive subset. Every spacing family that ships variants ships
 * exactly these steps at every tier. This is the rule that replaces the audit's
 * hand-picked coverage: one list, applied uniformly.
 */
// Steps 3, 12 and 16 dropped from the responsive set on 2026-09-13 to stay under the 50KB
// gzip ceiling (cut order in the generator design, item 1). md:p-3 is the
// least-missed responsive step and nothing shipped used a responsive 16; base steps are unaffected.
export const SPACE_RESP = ['0', '1', '2', '4', '6', '8'];

/** Responsive subset for side-specific spacing. */
export const SPACE_RESP_SIDE = ['0', '2', '4', '6', '8'];

/* -------------------------------------------------------------------------
   Variant model
   ------------------------------------------------------------------------- */

/** min-width breakpoints, emitted in this order. */
export const breakpoints = {
  sm: { px: 640, tiers: ['A', 'B'] },
  md: { px: 768, tiers: ['A', 'B'] },
  lg: { px: 1024, tiers: ['A', 'B'] },
  xl: { px: 1280, tiers: ['A', 'B'] },
  // 2xl (1536px, tier A only) dropped on 2026-09-13 to pay for the chart
  // palette and the tone attribute. Zero usages anywhere in the repo: no site
  // page, no registry component, variant, template or blueprint and no doc
  // wrote a 2xl: class, so the whole tier existed for nobody. xl at 1280px is
  // the widest decision the library's own layouts make. Note it is also the
  // only class family whose name starts with a digit, so nothing left needs
  // the six-hex-digit ident escape; css-names.mjs keeps reading it so an
  // author's stale 2xl:flex still gets a suggestion from the validator.
};

/**
 * Container-query tiers, emitted after the breakpoints so a container query
 * beats a viewport query at equal specificity. The nearest ancestor carrying
 * `cq` or `cq-inline` is the query container.
 *
 * Bare `cq:` is gone. It fired at 380px for some classes and 600px for others,
 * which is not a variant, it is a bug with a name. Nobody consumes the library
 * yet, so there is no alias release; rename-map.json carries the per-class
 * mapping a codemod needs.
 */
export const containerTiers = {
  'cq-sm': 380,
  'cq-md': 600,
  'cq-lg': 900,
};

/**
 * State variants. Emitted last, in this order. Each carries a pseudo-class or
 * a descendant selector, so its specificity is at least 0,2,0 and it beats the
 * base and breakpoint copies regardless of source order.
 */
export const stateVariants = [
  'hover',
  'focus',
  'focus-visible',
  'active',
  'disabled',
  'group-hover',
  'dark',
  'print',
  'motion-safe',
  'motion-reduce',
  'first',
  'last',
];

/** Named bundles a family opts into, so the tier table stays short. */
export const stateSets = {
  interactive: ['hover', 'focus-visible', 'active', 'group-hover'],
  focusOnly: ['focus', 'focus-visible'],
  // odd and even dropped on 2026-09-13 to pay for the chart palette and the
  // tone attribute, in the same cut as the 2xl breakpoint. Zero usages
  // anywhere in the repo: zebra striping is a table concern and tables.css
  // already ships it as a component rule, so no markup ever reached for
  // odd:bg-surface-1. first and last stay; both are used.
  structural: ['first', 'last'],
  theme: ['dark'],
  motion: ['motion-safe', 'motion-reduce'],
  print: ['print'],
};

/** Copies a tier produces, for the budget report. */
export const tiers = {
  A: { breakpoints: true, containers: true, note: 'structural families: layout decisions that change per viewport and per container' },
  B: { breakpoints: true, containers: false, note: 'spacing and sizing: change per viewport, rarely per container' },
  C: { breakpoints: false, containers: false, note: 'base only: one declaration, no responsive story' },
};

/* -------------------------------------------------------------------------
   New tokens tokens.css must declare before the generated CSS is valid.
   `.` is not a legal character in a custom property name, so `p-0.5` reads
   --ai-space-0-5.
   ------------------------------------------------------------------------- */

export const tokensToAdd = {
  '--ai-space-px': '1px',
  '--ai-space-0-5': '0.125rem',
  '--ai-space-1-5': '0.375rem',
  '--ai-space-2-5': '0.625rem',
  '--ai-space-3-5': '0.875rem',
  '--ai-space-7': '1.75rem',
  '--ai-space-9': '2.25rem',
  '--ai-space-11': '2.75rem',
  '--ai-space-14': '3.5rem',
  '--ai-space-28': '7rem',
  '--ai-space-36': '9rem',
  '--ai-space-40': '10rem',
  '--ai-space-48': '12rem',
  '--ai-space-56': '14rem',
  '--ai-space-64': '16rem',
  '--ai-space-72': '18rem',
  '--ai-space-80': '20rem',
  '--ai-space-96': '24rem',
};

/**
 * tokens.css has no z-index scale today; utilities.css hard-codes 0/10/20/30/
 * 40/50 and `.sticky` hard-codes 40. The z family and `sticky-top` read these.
 * Separate export so the spacing answer stays exactly what was asked for.
 */
export const tokensToAddZ = {
  '--ai-z-base': '0',
  '--ai-z-raised': '10',
  '--ai-z-dropdown': '20',
  '--ai-z-sticky': '30',
  '--ai-z-overlay': '40',
  '--ai-z-modal': '50',
  '--ai-z-toast': '60',
};

/* -------------------------------------------------------------------------
   Families
   ------------------------------------------------------------------------- */

export const families = [
  /* ===== P0 display and box ============================================== */
  {
    id: 'display',
    family: 'display',
    priority: 'P0',
    tier: 'A',
    states: ['interactive', 'theme', 'print'],
    prefix: null,
    props: ['display'],
    values: {
      block: 'block',
      'inline-block': 'inline-block',
      inline: 'inline',
      flex: 'flex',
      'inline-flex': 'inline-flex',
      grid: 'grid',
      'inline-grid': 'inline-grid',
      contents: 'contents',
      'flow-root': 'flow-root',
      'list-item': 'list-item',
      'inline-table': 'inline-table',
      'table-row': 'table-row',
      'table-cell': 'table-cell',
      'table-caption': 'table-caption',
      hidden: 'none',
    },
    variantValues: ['block', 'inline-block', 'inline', 'flex', 'inline-flex', 'grid', 'inline-grid', 'contents', 'hidden'],
    notes:
      'No bare `table` display utility: .table is the data-table component in components/tables.css and the two would collide. `hidden` is declared last so `class="flex hidden"` hides at equal specificity. No !important anywhere: the utilities layer is last in index.css, so every utility already outranks every component.',
  },
  {
    id: 'visibility',
    family: 'display',
    priority: 'P1',
    tier: 'B',
    states: ['print'],
    prefix: null,
    props: ['visibility'],
    values: { visible: 'visible', invisible: 'hidden' },
    variantValues: 'all',
    notes: 'Bootstrap\'s `collapse` (visibility: collapse) is omitted. .collapse is the details/summary disclosure component in components/extras.css; collapse-cell was considered and rejected as a name nobody would guess.',
  },
  {
    id: 'isolation',
    family: 'layout',
    priority: 'P2',
    tier: 'C',
    prefix: null,
    props: ['isolation'],
    values: { isolate: 'isolate', 'isolation-auto': 'auto' },
  },
  {
    id: 'float',
    family: 'layout',
    priority: 'P2',
    tier: 'C',
    prefix: 'float',
    props: ['float'],
    values: { start: 'inline-start', end: 'inline-end', left: 'left', right: 'right', none: 'none' },
  },
  {
    id: 'clear',
    family: 'layout',
    priority: 'P2',
    tier: 'C',
    prefix: 'clear',
    props: ['clear'],
    values: { start: 'inline-start', end: 'inline-end', left: 'left', right: 'right', both: 'both', none: 'none' },
  },

  /* ===== P0 flex ========================================================== */
  {
    id: 'flex-direction',
    family: 'flex',
    priority: 'P0',
    tier: 'A',
    prefix: 'flex',
    props: ['flex-direction'],
    values: { row: 'row', 'row-reverse': 'row-reverse', col: 'column', 'col-reverse': 'column-reverse' },
    variantValues: 'all',
  },
  {
    id: 'flex-wrap',
    family: 'flex',
    priority: 'P0',
    tier: 'A',
    prefix: 'flex',
    props: ['flex-wrap'],
    values: { wrap: 'wrap', 'wrap-reverse': 'wrap-reverse', nowrap: 'nowrap' },
    variantValues: 'all',
  },
  {
    id: 'flex',
    family: 'flex',
    priority: 'P0',
    tier: 'B',
    prefix: 'flex',
    props: ['flex'],
    values: { 1: '1 1 0%', auto: '1 1 auto', initial: '0 1 auto', none: 'none' },
    variantValues: 'all',
  },
  {
    id: 'flex-grow',
    family: 'flex',
    priority: 'P0',
    tier: 'B',
    prefix: null,
    props: ['flex-grow'],
    values: { grow: '1', 'grow-0': '0' },
    variantValues: 'all',
  },
  {
    id: 'flex-shrink',
    family: 'flex',
    priority: 'P0',
    tier: 'B',
    prefix: null,
    props: ['flex-shrink'],
    values: { shrink: '1', 'shrink-0': '0' },
    variantValues: 'all',
  },
  {
    id: 'flex-basis',
    family: 'flex',
    priority: 'P1',
    tier: 'B',
    prefix: 'basis',
    props: ['flex-basis'],
    values: {
      0: '0px', auto: 'auto', full: '100%',
      '1/2': '50%', '1/3': '33.333333%', '2/3': '66.666667%', '1/4': '25%', '3/4': '75%',
    },
    variantValues: ['0', 'auto', 'full', '1/2', '1/3', '2/3'],
  },
  {
    id: 'align-items',
    family: 'flex',
    priority: 'P0',
    tier: 'A',
    prefix: 'items',
    props: ['align-items'],
    values: { start: 'flex-start', center: 'center', end: 'flex-end', baseline: 'baseline', stretch: 'stretch' },
    variantValues: 'all',
  },
  {
    id: 'justify-content',
    family: 'flex',
    priority: 'P0',
    tier: 'A',
    prefix: 'justify',
    props: ['justify-content'],
    values: {
      start: 'flex-start', center: 'center', end: 'flex-end',
      between: 'space-between', around: 'space-around', evenly: 'space-evenly', normal: 'normal',
    },
    variantValues: 'all',
  },
  {
    id: 'align-self',
    family: 'flex',
    priority: 'P0',
    tier: 'A',
    prefix: 'self',
    props: ['align-self'],
    values: { auto: 'auto', start: 'flex-start', center: 'center', end: 'flex-end', stretch: 'stretch', baseline: 'baseline' },
    variantValues: 'all',
  },
  {
    id: 'align-content',
    family: 'flex',
    priority: 'P1',
    tier: 'B',
    prefix: 'content',
    props: ['align-content'],
    values: {
      start: 'flex-start', center: 'center', end: 'flex-end', between: 'space-between',
      around: 'space-around', evenly: 'space-evenly', stretch: 'stretch', baseline: 'baseline',
    },
    variantValues: ['start', 'center', 'end', 'between'],
  },
  {
    id: 'place-items',
    family: 'flex',
    priority: 'P1',
    tier: 'A',
    prefix: 'place-items',
    props: ['place-items'],
    values: { start: 'start', center: 'center', end: 'end', stretch: 'stretch', baseline: 'baseline' },
    variantValues: ['start', 'center', 'end', 'stretch'],
  },
  {
    id: 'place-content',
    family: 'flex',
    priority: 'P1',
    tier: 'B',
    prefix: 'place-content',
    props: ['place-content'],
    values: {
      center: 'center', start: 'start', end: 'end', between: 'space-between',
      around: 'space-around', evenly: 'space-evenly', stretch: 'stretch',
    },
    variantValues: ['center', 'start', 'end', 'between'],
  },
  {
    id: 'place-self',
    family: 'flex',
    priority: 'P1',
    tier: 'B',
    prefix: 'place-self',
    props: ['place-self'],
    values: { auto: 'auto', start: 'start', center: 'center', end: 'end', stretch: 'stretch' },
    variantValues: ['start', 'center', 'end', 'stretch'],
  },
  {
    id: 'order',
    family: 'flex',
    priority: 'P0',
    tier: 'B',
    prefix: 'order',
    props: ['order'],
    values: { ...map(range(1, 12), String), first: '-9999', last: '9999', none: '0' },
    variantValues: ['1', '2', '3', '4', '5', '6', 'first', 'last', 'none'],
    notes: 'order-* is flexbox and grid only. The ecommerce order-tracker component classes (order-head, order-step, order-pip, ...) are renamed orderline-* so this prefix is unambiguous for both humans and codemods.',
  },

  /* ===== P0 grid ========================================================== */
  {
    id: 'grid-template-columns',
    family: 'grid',
    priority: 'P0',
    tier: 'A',
    prefix: 'grid-cols',
    props: ['grid-template-columns'],
    values: {
      ...map(range(1, 12), (n) => `repeat(${n}, minmax(0, 1fr))`),
      none: 'none',
      subgrid: 'subgrid',
    },
    variantValues: ['1', '2', '3', '4', '5', '6', '8', '12', 'none'],
  },
  {
    id: 'grid-template-rows',
    family: 'grid',
    priority: 'P1',
    tier: 'B',
    prefix: 'grid-rows',
    props: ['grid-template-rows'],
    values: { ...map(range(1, 6), (n) => `repeat(${n}, minmax(0, 1fr))`), none: 'none', subgrid: 'subgrid' },
    variantValues: ['1', '2', '3', '4', 'none'],
  },
  {
    id: 'col-span',
    family: 'grid',
    priority: 'P0',
    tier: 'A',
    prefix: 'col',
    props: ['grid-column'],
    values: {
      auto: 'auto',
      ...Object.fromEntries(range(1, 12).map((n) => [`span-${n}`, `span ${n} / span ${n}`])),
      'span-full': '1 / -1',
    },
    variantValues: [...range(1, 12).map((n) => `span-${n}`), 'span-full', 'auto'],
  },
  {
    id: 'row-span',
    family: 'grid',
    priority: 'P1',
    tier: 'B',
    prefix: 'row',
    props: ['grid-row'],
    values: {
      auto: 'auto',
      ...Object.fromEntries(range(1, 6).map((n) => [`span-${n}`, `span ${n} / span ${n}`])),
      'span-full': '1 / -1',
    },
    variantValues: ['span-1', 'span-2', 'span-3', 'span-full', 'auto'],
  },
  {
    id: 'col-start',
    family: 'grid',
    priority: 'P1',
    tier: 'B',
    prefix: 'col-start',
    props: ['grid-column-start'],
    values: { ...map(range(1, 13), String), auto: 'auto' },
    variantValues: ['1', '2', '3', '4', '5', '7', 'auto'],
  },
  {
    id: 'col-end',
    family: 'grid',
    priority: 'P1',
    tier: 'B',
    prefix: 'col-end',
    props: ['grid-column-end'],
    values: { ...map(range(1, 13), String), auto: 'auto' },
    variantValues: ['1', '4', '7', '13', 'auto'],
  },
  {
    id: 'row-start',
    family: 'grid',
    priority: 'P2',
    tier: 'C',
    prefix: 'row-start',
    props: ['grid-row-start'],
    values: { ...map(range(1, 7), String), auto: 'auto' },
  },
  {
    id: 'row-end',
    family: 'grid',
    priority: 'P2',
    tier: 'C',
    prefix: 'row-end',
    props: ['grid-row-end'],
    values: { ...map(range(1, 7), String), auto: 'auto' },
  },
  {
    id: 'grid-auto-flow',
    family: 'grid',
    priority: 'P1',
    tier: 'B',
    prefix: 'grid-flow',
    props: ['grid-auto-flow'],
    values: { row: 'row', col: 'column', dense: 'dense', 'row-dense': 'row dense', 'col-dense': 'column dense' },
    variantValues: ['row', 'col'],
  },
  {
    id: 'grid-auto-columns',
    family: 'grid',
    priority: 'P2',
    tier: 'C',
    prefix: 'auto-cols',
    props: ['grid-auto-columns'],
    values: { auto: 'auto', min: 'min-content', max: 'max-content', fr: 'minmax(0, 1fr)' },
  },
  {
    id: 'grid-auto-rows',
    family: 'grid',
    priority: 'P2',
    tier: 'C',
    prefix: 'auto-rows',
    props: ['grid-auto-rows'],
    values: { auto: 'auto', min: 'min-content', max: 'max-content', fr: 'minmax(0, 1fr)' },
  },

  /* ===== P0 spacing ======================================================= */
  {
    id: 'gap',
    family: 'spacing',
    priority: 'P0',
    tier: 'A',
    prefix: 'gap',
    props: ['gap'],
    values: map(SPACE, spaceToken),
    variantValues: [...SPACE_RESP, '10'],
  },
  {
    id: 'gap-x',
    family: 'spacing',
    priority: 'P1',
    tier: 'B',
    prefix: 'gap-x',
    props: ['column-gap'],
    values: map(SPACE_SIDE, spaceToken),
    variantValues: SPACE_RESP_SIDE,
  },
  {
    id: 'gap-y',
    family: 'spacing',
    priority: 'P1',
    tier: 'B',
    prefix: 'gap-y',
    props: ['row-gap'],
    values: map(SPACE_SIDE, spaceToken),
    variantValues: SPACE_RESP_SIDE,
  },
  {
    id: 'padding',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'p',
    props: ['padding'],
    values: map(SPACE, spaceToken),
    variantValues: SPACE_RESP,
  },
  {
    id: 'padding-x',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'px',
    props: ['padding-left', 'padding-right'],
    values: map(SPACE, spaceToken),
    variantValues: SPACE_RESP,
  },
  {
    id: 'padding-y',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'py',
    props: ['padding-top', 'padding-bottom'],
    values: map(SPACE, spaceToken),
    variantValues: SPACE_RESP,
  },
  {
    id: 'padding-top',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'pt',
    props: ['padding-top'],
    values: map(SPACE_SIDE, spaceToken),
    variantValues: SPACE_RESP_SIDE,
  },
  {
    id: 'padding-bottom',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'pb',
    props: ['padding-bottom'],
    values: map(SPACE_SIDE, spaceToken),
    variantValues: SPACE_RESP_SIDE,
  },
  {
    id: 'padding-inline-start',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'ps',
    props: ['padding-inline-start'],
    values: map(SPACE_SIDE, spaceToken),
    variantValues: SPACE_RESP_SIDE,
  },
  {
    id: 'padding-inline-end',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'pe',
    props: ['padding-inline-end'],
    values: map(SPACE_SIDE, spaceToken),
    variantValues: SPACE_RESP_SIDE,
  },
  {
    id: 'padding-left',
    family: 'spacing',
    priority: 'P1',
    tier: 'C',
    prefix: 'pl',
    props: ['padding-left'],
    values: map(SPACE_SIDE, spaceToken),
    notes: 'Physical sides stay base-only. ps/pe carry the responsive story so RTL layouts get it for free.',
  },
  {
    id: 'padding-right',
    family: 'spacing',
    priority: 'P1',
    tier: 'C',
    prefix: 'pr',
    props: ['padding-right'],
    values: map(SPACE_SIDE, spaceToken),
  },
  {
    id: 'margin',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'm',
    props: ['margin'],
    values: { ...map(SPACE, spaceToken), auto: 'auto' },
    variantValues: [...SPACE_RESP, 'auto'],
  },
  {
    id: 'margin-x',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'mx',
    props: ['margin-left', 'margin-right'],
    values: { ...map(SPACE, spaceToken), auto: 'auto' },
    variantValues: [...SPACE_RESP, 'auto'],
  },
  {
    id: 'margin-y',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'my',
    props: ['margin-top', 'margin-bottom'],
    values: { ...map(SPACE, spaceToken), auto: 'auto' },
    variantValues: [...SPACE_RESP, 'auto'],
  },
  {
    id: 'margin-top',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'mt',
    props: ['margin-top'],
    values: { ...map(SPACE_SIDE, spaceToken), auto: 'auto' },
    variantValues: [...SPACE_RESP_SIDE, 'auto'],
  },
  {
    id: 'margin-bottom',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'mb',
    props: ['margin-bottom'],
    values: { ...map(SPACE_SIDE, spaceToken), auto: 'auto' },
    variantValues: [...SPACE_RESP_SIDE, 'auto'],
  },
  {
    id: 'margin-inline-start',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'ms',
    props: ['margin-inline-start'],
    values: { ...map(SPACE_SIDE, spaceToken), auto: 'auto' },
    variantValues: [...SPACE_RESP_SIDE, 'auto'],
  },
  {
    id: 'margin-inline-end',
    family: 'spacing',
    priority: 'P0',
    tier: 'B',
    prefix: 'me',
    props: ['margin-inline-end'],
    values: { ...map(SPACE_SIDE, spaceToken), auto: 'auto' },
    variantValues: [...SPACE_RESP_SIDE, 'auto'],
  },
  {
    id: 'margin-left',
    family: 'spacing',
    priority: 'P1',
    tier: 'B',
    prefix: 'ml',
    props: ['margin-left'],
    values: { ...map(SPACE_SIDE, spaceToken), auto: 'auto' },
    variantValues: ['0', 'auto'],
  },
  {
    id: 'margin-right',
    family: 'spacing',
    priority: 'P1',
    tier: 'B',
    prefix: 'mr',
    props: ['margin-right'],
    values: { ...map(SPACE_SIDE, spaceToken), auto: 'auto' },
    variantValues: ['0', 'auto'],
  },
  {
    id: 'margin-negative',
    family: 'spacing',
    priority: 'P1',
    tier: 'C',
    prefix: '-m',
    props: ['margin'],
    values: map(SPACE_NEG, negSpace),
  },
  {
    id: 'margin-x-negative',
    family: 'spacing',
    priority: 'P1',
    tier: 'C',
    prefix: '-mx',
    props: ['margin-left', 'margin-right'],
    values: map(SPACE_NEG, negSpace),
  },
  {
    id: 'margin-y-negative',
    family: 'spacing',
    priority: 'P1',
    tier: 'C',
    prefix: '-my',
    props: ['margin-top', 'margin-bottom'],
    values: map(SPACE_NEG, negSpace),
  },
  {
    id: 'margin-top-negative',
    family: 'spacing',
    priority: 'P1',
    tier: 'C',
    prefix: '-mt',
    props: ['margin-top'],
    values: map(SPACE_NEG, negSpace),
  },
  {
    id: 'margin-bottom-negative',
    family: 'spacing',
    priority: 'P1',
    tier: 'C',
    prefix: '-mb',
    props: ['margin-bottom'],
    values: map(SPACE_NEG, negSpace),
  },
  {
    id: 'margin-inline-start-negative',
    family: 'spacing',
    priority: 'P1',
    tier: 'C',
    prefix: '-ms',
    props: ['margin-inline-start'],
    values: map(SPACE_NEG, negSpace),
  },
  {
    id: 'margin-inline-end-negative',
    family: 'spacing',
    priority: 'P1',
    tier: 'C',
    prefix: '-me',
    props: ['margin-inline-end'],
    values: map(SPACE_NEG, negSpace),
  },
  {
    id: 'margin-left-negative',
    family: 'spacing',
    priority: 'P2',
    tier: 'C',
    prefix: '-ml',
    props: ['margin-left'],
    values: map(SPACE_NEG, negSpace),
  },
  {
    id: 'margin-right-negative',
    family: 'spacing',
    priority: 'P2',
    tier: 'C',
    prefix: '-mr',
    props: ['margin-right'],
    values: map(SPACE_NEG, negSpace),
  },
  {
    id: 'space-y',
    family: 'spacing',
    priority: 'P1',
    tier: 'C',
    prefix: 'space-y',
    props: ['margin-block-start'],
    values: map(SPACE_RESP, spaceToken),
    selectorSuffix: ' > * + *',
    notes: 'Owner-stack helper. Uses the logical property so it flips with writing-mode. Base tier only: a responsive space-y would need the same override cascade that makes Tailwind\'s version fragile.',
  },
  {
    id: 'space-x',
    family: 'spacing',
    priority: 'P1',
    tier: 'C',
    prefix: 'space-x',
    props: ['margin-inline-start'],
    values: map(SPACE_RESP, spaceToken),
    selectorSuffix: ' > * + *',
  },

  /* ===== P0 sizing ======================================================== */
  {
    id: 'width',
    family: 'sizing',
    priority: 'P0',
    tier: 'B',
    prefix: 'w',
    props: ['width'],
    values: {
      ...map(SPACE, spaceToken),
      auto: 'auto', full: '100%', screen: '100vw', dvw: '100dvw',
      min: 'min-content', max: 'max-content', fit: 'fit-content',
      '1/2': '50%', '1/3': '33.333333%', '2/3': '66.666667%',
      '1/4': '25%', '2/4': '50%', '3/4': '75%',
      '1/5': '20%', '2/5': '40%', '3/5': '60%', '4/5': '80%',
      '1/6': '16.666667%', '5/6': '83.333333%',
      '1/12': '8.333333%', '5/12': '41.666667%', '7/12': '58.333333%', '11/12': '91.666667%',
    },
    variantValues: ['auto', 'full', 'screen', 'min', 'max', 'fit', '1/2', '1/3', '2/3', '1/4', '3/4'],
  },
  {
    id: 'height',
    family: 'sizing',
    priority: 'P0',
    tier: 'B',
    prefix: 'h',
    props: ['height'],
    values: {
      ...map(SPACE, spaceToken),
      auto: 'auto', full: '100%', screen: '100vh', dvh: '100dvh',
      min: 'min-content', max: 'max-content', fit: 'fit-content',
      '1/2': '50%', '1/3': '33.333333%', '2/3': '66.666667%',
    },
    variantValues: ['auto', 'full', 'screen', 'min', 'max', 'fit'],
  },
  {
    id: 'size',
    family: 'sizing',
    priority: 'P1',
    tier: 'C',
    prefix: 'size',
    props: ['width', 'height'],
    values: { ...map(SPACE, spaceToken), auto: 'auto', full: '100%', fit: 'fit-content' },
    notes: 'Square sizing. Base only: icons and avatars do not change size per breakpoint often enough to pay six copies of a 35-step scale.',
  },
  {
    id: 'min-width',
    family: 'sizing',
    priority: 'P1',
    tier: 'C',
    prefix: 'min-w',
    props: ['min-width'],
    values: { 0: '0px', full: '100%', min: 'min-content', max: 'max-content', fit: 'fit-content', screen: '100vw' },
  },
  {
    id: 'min-height',
    family: 'sizing',
    priority: 'P1',
    tier: 'C',
    prefix: 'min-h',
    props: ['min-height'],
    values: { 0: '0px', full: '100%', screen: '100vh', dvh: '100dvh', min: 'min-content', max: 'max-content', fit: 'fit-content' },
  },
  {
    id: 'max-width',
    family: 'sizing',
    priority: 'P0',
    tier: 'B',
    prefix: 'max-w',
    props: ['max-width'],
    values: {
      none: 'none', 0: '0px', full: '100%', min: 'min-content', max: 'max-content', fit: 'fit-content',
      prose: '65ch', screen: '100vw',
      xs: '20rem', sm: '24rem', md: '28rem', lg: '32rem', xl: '36rem',
      '2xl': '42rem', '3xl': '48rem', '4xl': '56rem', '5xl': '64rem', '6xl': '72rem', '7xl': '80rem',
    },
    variantValues: ['none', 'full', 'prose', 'md', 'lg', 'xl', '3xl', '5xl'],
  },
  {
    id: 'max-height',
    family: 'sizing',
    priority: 'P1',
    tier: 'C',
    prefix: 'max-h',
    props: ['max-height'],
    values: { none: 'none', full: '100%', screen: '100vh', dvh: '100dvh', min: 'min-content', max: 'max-content', fit: 'fit-content' },
  },
  {
    id: 'aspect-ratio',
    family: 'layout',
    priority: 'P1',
    tier: 'B',
    prefix: 'aspect',
    props: ['aspect-ratio'],
    values: { auto: 'auto', square: '1 / 1', video: '16 / 9', '4/3': '4 / 3', '3/2': '3 / 2', '2/1': '2 / 1', portrait: '3 / 4' },
    variantValues: ['auto', 'square', 'video'],
  },
  {
    id: 'container-width',
    family: 'layout',
    priority: 'P1',
    tier: 'C',
    prefix: 'container-w',
    props: ['max-width'],
    values: { sm: '768px', md: '1024px', lg: '1440px', xl: '1600px', full: '100%' },
    notes: 'These are the old hard-cap container-sm..container-xl, renamed. The new container-sm..container-2xl are Bootstrap-shaped (fluid, then capped at each breakpoint) and live in utilities.extra.css because a cascade of caps is not a value map.',
  },
  {
    id: 'container-type',
    family: 'layout',
    priority: 'P0',
    tier: 'C',
    prefix: null,
    props: ['container-type'],
    values: { cq: 'inline-size', 'cq-inline': 'inline-size', 'cq-normal': 'normal' },
    notes: 'Container-type setters for the cq-sm/cq-md/cq-lg variants. `container-type: size` is deliberately absent: it requires both dimensions to be contained and silently collapses content height. `container-inline` is renamed cq-inline so the setter and the variants share one prefix.',
  },

  /* ===== P0 position ====================================================== */
  {
    id: 'position',
    family: 'position',
    priority: 'P0',
    tier: 'B',
    prefix: null,
    props: ['position'],
    values: {
      static: 'static',
      fixed: 'fixed',
      absolute: 'absolute',
      relative: 'relative',
      sticky: 'sticky',
      'sticky-top': { position: 'sticky', top: '0', 'z-index': 'var(--ai-z-sticky)' },
    },
    variantValues: ['static', 'fixed', 'absolute', 'relative', 'sticky'],
    notes: '`sticky` is position-only so it composes with any top-* and z-* value. `sticky-top` is the opinionated bundle the old `sticky` used to be: sticky plus top:0 plus the sticky z token. Splitting them means `sticky top-4` finally works.',
  },
  {
    id: 'inset',
    family: 'position',
    priority: 'P1',
    tier: 'B',
    prefix: 'inset',
    props: ['inset'],
    values: { 0: '0', auto: 'auto', px: spaceToken('px'), ...map(['1', '2', '3', '4', '6', '8'], spaceToken), full: '100%' },
    variantValues: ['0', 'auto'],
  },
  {
    id: 'inset-x',
    family: 'position',
    priority: 'P1',
    tier: 'C',
    prefix: 'inset-x',
    props: ['left', 'right'],
    values: { 0: '0', auto: 'auto', ...map(['1', '2', '3', '4', '6', '8'], spaceToken), full: '100%' },
  },
  {
    id: 'inset-y',
    family: 'position',
    priority: 'P1',
    tier: 'C',
    prefix: 'inset-y',
    props: ['top', 'bottom'],
    values: { 0: '0', auto: 'auto', ...map(['1', '2', '3', '4', '6', '8'], spaceToken), full: '100%' },
  },
  {
    id: 'top',
    family: 'position',
    priority: 'P1',
    tier: 'C',
    prefix: 'top',
    props: ['top'],
    values: { 0: '0', auto: 'auto', px: spaceToken('px'), ...map(['1', '2', '3', '4', '6', '8', '12', '16'], spaceToken), full: '100%', half: '50%' },
  },
  {
    id: 'bottom',
    family: 'position',
    priority: 'P1',
    tier: 'C',
    prefix: 'bottom',
    props: ['bottom'],
    values: { 0: '0', auto: 'auto', px: spaceToken('px'), ...map(['1', '2', '3', '4', '6', '8', '12', '16'], spaceToken), full: '100%', half: '50%' },
  },
  {
    id: 'left',
    family: 'position',
    priority: 'P1',
    tier: 'C',
    prefix: 'left',
    props: ['left'],
    values: { 0: '0', auto: 'auto', ...map(['1', '2', '3', '4', '6', '8'], spaceToken), full: '100%', half: '50%' },
  },
  {
    id: 'right',
    family: 'position',
    priority: 'P1',
    tier: 'C',
    prefix: 'right',
    props: ['right'],
    values: { 0: '0', auto: 'auto', ...map(['1', '2', '3', '4', '6', '8'], spaceToken), full: '100%', half: '50%' },
  },
  {
    id: 'inset-inline-start',
    family: 'position',
    priority: 'P1',
    tier: 'C',
    prefix: 'start',
    props: ['inset-inline-start'],
    values: { 0: '0', auto: 'auto', ...map(['1', '2', '3', '4', '6', '8'], spaceToken), full: '100%', half: '50%' },
  },
  {
    id: 'inset-inline-end',
    family: 'position',
    priority: 'P1',
    tier: 'C',
    prefix: 'end',
    props: ['inset-inline-end'],
    values: { 0: '0', auto: 'auto', ...map(['1', '2', '3', '4', '6', '8'], spaceToken), full: '100%', half: '50%' },
  },
  {
    id: 'z-index',
    family: 'position',
    priority: 'P0',
    tier: 'B',
    prefix: 'z',
    props: ['z-index'],
    values: {
      0: '0', 10: '10', 20: '20', 30: '30', 40: '40', 50: '50', auto: 'auto',
      base: 'var(--ai-z-base)', raised: 'var(--ai-z-raised)', dropdown: 'var(--ai-z-dropdown)',
      sticky: 'var(--ai-z-sticky)', overlay: 'var(--ai-z-overlay)', modal: 'var(--ai-z-modal)', toast: 'var(--ai-z-toast)',
    },
    variantValues: ['0', '10', '20', '30', '40', '50', 'auto'],
    notes: 'Numeric steps keep Tailwind parity; the named steps read the new --ai-z-* tokens so components and utilities agree on the stack.',
  },

  /* ===== P0 typography ==================================================== */
  {
    id: 'text-align',
    family: 'typography',
    priority: 'P0',
    tier: 'A',
    prefix: 'text',
    props: ['text-align'],
    values: { left: 'left', center: 'center', right: 'right', start: 'start', end: 'end', justify: 'justify' },
    variantValues: 'all',
  },
  {
    id: 'font-size',
    family: 'typography',
    priority: 'P0',
    tier: 'B',
    prefix: 'text',
    props: [],
    values: {
      xs: { 'font-size': '0.75rem', 'line-height': '1rem' },
      sm: { 'font-size': '0.875rem', 'line-height': '1.25rem' },
      base: { 'font-size': '1rem', 'line-height': '1.5rem' },
      lg: { 'font-size': '1.125rem', 'line-height': '1.75rem' },
      xl: { 'font-size': '1.25rem', 'line-height': '1.75rem' },
      '2xl': { 'font-size': '1.5rem', 'line-height': '2rem' },
      '3xl': { 'font-size': '1.875rem', 'line-height': '2.25rem' },
      '4xl': { 'font-size': '2.25rem', 'line-height': '2.5rem' },
      '5xl': { 'font-size': '3rem', 'line-height': '1.1' },
      '6xl': { 'font-size': '3.75rem', 'line-height': '1.05' },
      '7xl': { 'font-size': '4.5rem', 'line-height': '1' },
    },
    variantValues: ['sm', 'base', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl'],
  },
  {
    id: 'font-weight',
    family: 'typography',
    priority: 'P0',
    tier: 'C',
    prefix: 'font',
    props: ['font-weight'],
    values: { light: '300', normal: '400', medium: '500', semibold: '600', bold: '700', extrabold: '800' },
  },
  {
    id: 'font-family',
    family: 'typography',
    priority: 'P0',
    tier: 'C',
    prefix: 'font',
    props: ['font-family'],
    values: { sans: 'var(--ai-font-sans)', mono: 'var(--ai-font-mono)', display: 'var(--ai-font-display)', serif: 'var(--ai-font-serif)' },
  },
  {
    id: 'font-style',
    family: 'typography',
    priority: 'P1',
    tier: 'C',
    prefix: null,
    props: ['font-style'],
    values: { italic: 'italic', 'not-italic': 'normal' },
  },
  {
    id: 'line-height',
    family: 'typography',
    priority: 'P0',
    tier: 'C',
    prefix: 'leading',
    props: ['line-height'],
    values: { none: '1', tight: '1.2', snug: '1.35', normal: '1.5', relaxed: '1.625', loose: '2' },
  },
  {
    id: 'letter-spacing',
    family: 'typography',
    priority: 'P0',
    tier: 'C',
    prefix: 'tracking',
    props: ['letter-spacing'],
    values: { tighter: '-0.035em', tight: '-0.02em', normal: '0', wide: '0.025em', wider: '0.05em', widest: '0.1em' },
  },
  {
    id: 'text-transform',
    family: 'typography',
    priority: 'P1',
    tier: 'C',
    prefix: null,
    props: ['text-transform'],
    values: { uppercase: 'uppercase', lowercase: 'lowercase', capitalize: 'capitalize', 'normal-case': 'none' },
  },
  {
    id: 'text-wrap',
    family: 'typography',
    priority: 'P1',
    tier: 'C',
    prefix: 'text',
    props: ['text-wrap'],
    values: { balance: 'balance', pretty: 'pretty', nowrap: 'nowrap', wrap: 'wrap' },
    notes: 'The audit listed text-balance as a keeper. It is a one-property value map, so it belongs in the matrix; keeping it hand-written would mean text-pretty and text-nowrap never arrive.',
  },
  {
    id: 'white-space',
    family: 'typography',
    priority: 'P1',
    tier: 'C',
    prefix: 'whitespace',
    props: ['white-space'],
    values: { normal: 'normal', nowrap: 'nowrap', pre: 'pre', 'pre-line': 'pre-line', 'pre-wrap': 'pre-wrap', 'break-spaces': 'break-spaces' },
  },
  {
    id: 'word-break',
    family: 'typography',
    priority: 'P1',
    tier: 'C',
    prefix: null,
    props: [],
    values: {
      'break-normal': { 'overflow-wrap': 'normal', 'word-break': 'normal' },
      'break-words': { 'overflow-wrap': 'break-word' },
      'break-all': { 'word-break': 'break-all' },
      'break-keep': { 'word-break': 'keep-all' },
    },
  },
  {
    id: 'text-decoration',
    family: 'typography',
    priority: 'P1',
    tier: 'C',
    states: ['interactive'],
    prefix: null,
    props: ['text-decoration-line'],
    values: { underline: 'underline', overline: 'overline', 'line-through': 'line-through', 'no-underline': 'none' },
  },
  {
    id: 'text-decoration-thickness',
    family: 'typography',
    priority: 'P2',
    tier: 'C',
    prefix: 'decoration',
    props: ['text-decoration-thickness'],
    values: { auto: 'auto', from: 'from-font', 0: '0px', 1: '1px', 2: '2px' },
  },
  {
    id: 'underline-offset',
    family: 'typography',
    priority: 'P2',
    tier: 'C',
    prefix: 'underline-offset',
    props: ['text-underline-offset'],
    values: { auto: 'auto', 0: '0px', 1: '1px', 2: '2px', 4: '4px' },
  },
  {
    id: 'font-variant-numeric',
    family: 'typography',
    priority: 'P2',
    tier: 'C',
    prefix: null,
    props: ['font-variant-numeric'],
    values: { tabular: 'tabular-nums', 'proportional-nums': 'proportional-nums', 'lining-nums': 'lining-nums', 'oldstyle-nums': 'oldstyle-nums', 'normal-nums': 'normal' },
  },
  {
    id: 'list-style',
    family: 'typography',
    priority: 'P2',
    tier: 'C',
    prefix: 'list',
    props: ['list-style-type'],
    values: { none: 'none', disc: 'disc', decimal: 'decimal' },
  },
  {
    id: 'list-style-position',
    family: 'typography',
    priority: 'P2',
    tier: 'C',
    prefix: 'list',
    props: ['list-style-position'],
    values: { inside: 'inside', outside: 'outside' },
  },
  {
    id: 'vertical-align',
    family: 'typography',
    priority: 'P2',
    tier: 'C',
    prefix: 'align',
    props: ['vertical-align'],
    values: { baseline: 'baseline', top: 'top', middle: 'middle', bottom: 'bottom', 'text-top': 'text-top', 'text-bottom': 'text-bottom', sub: 'sub', super: 'super' },
  },

  /* ===== P0 colour ======================================================== */
  {
    id: 'text-color',
    family: 'typography',
    priority: 'P0',
    tier: 'C',
    states: ['interactive', 'theme'],
    prefix: 'text',
    props: ['color'],
    values: {
      primary: 'var(--ai-text-primary)',
      secondary: 'var(--ai-text-secondary)',
      muted: 'var(--ai-text-muted)',
      inverted: 'var(--ai-text-inverted)',
      accent: 'var(--ai-accent)',
      success: 'var(--ai-success)',
      warning: 'var(--ai-warning)',
      danger: 'var(--ai-danger)',
      info: 'var(--ai-info)',
      current: 'currentColor',
      inherit: 'inherit',
    },
    notes: 'text-* is overloaded three ways (alignment, size, colour). That is Tailwind\'s convention and the manifest disambiguates by family, but it is the single most confusing naming decision in the library and worth a reviewer challenge.',
  },
  {
    id: 'surface',
    family: 'effects',
    priority: 'P0',
    tier: 'C',
    states: ['interactive', 'theme', 'structural'],
    prefix: null,
    props: ['background-color'],
    values: {
      'surface-0': 'var(--ai-surface-0)',
      'surface-1': 'var(--ai-surface-1)',
      'surface-2': 'var(--ai-surface-2)',
      'surface-3': 'var(--ai-surface-3)',
    },
  },
  {
    id: 'background-color',
    family: 'effects',
    priority: 'P0',
    tier: 'C',
    states: ['interactive', 'theme'],
    prefix: 'bg',
    props: ['background-color'],
    values: {
      transparent: 'transparent',
      current: 'currentColor',
      bg: 'var(--ai-bg)',
      primary: 'var(--ai-primary)',
      accent: 'var(--ai-accent)',
      'accent-subtle': 'var(--ai-accent-subtle)',
      success: 'var(--ai-success)',
      'success-subtle': 'var(--ai-success-subtle)',
      warning: 'var(--ai-warning)',
      'warning-subtle': 'var(--ai-warning-subtle)',
      danger: 'var(--ai-danger)',
      'danger-subtle': 'var(--ai-danger-subtle)',
      info: 'var(--ai-info)',
      'info-subtle': 'var(--ai-info-subtle)',
    },
  },

  /* ===== P0 borders ======================================================= */
  {
    id: 'border-width',
    family: 'borders',
    priority: 'P0',
    tier: 'C',
    states: ['structural'],
    prefix: null,
    props: [],
    values: {
      border: { 'border-style': 'solid', 'border-width': '1px' },
      'border-0': { 'border-width': '0' },
      'border-2': { 'border-style': 'solid', 'border-width': '2px' },
      'border-t': { 'border-top-style': 'solid', 'border-top-width': '1px' },
      'border-t-0': { 'border-top-width': '0' },
      'border-b': { 'border-bottom-style': 'solid', 'border-bottom-width': '1px' },
      'border-b-0': { 'border-bottom-width': '0' },
      'border-l': { 'border-left-style': 'solid', 'border-left-width': '1px' },
      'border-l-0': { 'border-left-width': '0' },
      'border-r': { 'border-right-style': 'solid', 'border-right-width': '1px' },
      'border-r-0': { 'border-right-width': '0' },
      'border-is': { 'border-inline-start-style': 'solid', 'border-inline-start-width': '1px' },
      'border-ie': { 'border-inline-end-style': 'solid', 'border-inline-end-width': '1px' },
      'border-x': { 'border-inline-style': 'solid', 'border-inline-width': '1px' },
      'border-y': { 'border-block-style': 'solid', 'border-block-width': '1px' },
    },
    notes:
      'Width and style only, never the shorthand. The old `.border { border: 1px solid var(--ai-border) }` reset border-color, so `class="border border-accent"` only worked in one source order. The default colour moves to base.css as `*, ::before, ::after { border-color: var(--ai-border) }`, which is inert until something sets a width. That base.css edit is a prerequisite for this family and is the one change outside src/css/utilities.css that the generator cannot make.',
  },
  {
    id: 'border-color',
    family: 'borders',
    priority: 'P0',
    tier: 'C',
    states: ['interactive', 'theme', 'structural'],
    prefix: 'border',
    props: ['border-color'],
    values: {
      transparent: 'transparent',
      current: 'currentColor',
      subtle: 'var(--ai-border-subtle)',
      hover: 'var(--ai-border-hover)',
      strong: 'var(--ai-border-strong)',
      accent: 'var(--ai-accent)',
      success: 'var(--ai-success)',
      warning: 'var(--ai-warning)',
      danger: 'var(--ai-danger)',
    },
  },
  {
    id: 'border-style',
    family: 'borders',
    priority: 'P1',
    tier: 'C',
    prefix: 'border',
    props: ['border-style'],
    values: { solid: 'solid', dashed: 'dashed', dotted: 'dotted', 'style-none': 'none' },
    notes: '`border-none` would read as "no border" but only clears the style, leaving the width. Named border-style-none to make the narrower meaning obvious.',
  },
  {
    id: 'border-radius',
    family: 'borders',
    priority: 'P0',
    tier: 'B',
    prefix: 'rounded',
    props: ['border-radius'],
    values: {
      none: 'var(--ai-radius-none)',
      xs: 'var(--ai-radius-xs)',
      sm: 'var(--ai-radius-sm)',
      md: 'var(--ai-radius-md)',
      lg: 'var(--ai-radius-lg)',
      xl: 'var(--ai-radius-xl)',
      '2xl': 'var(--ai-radius-2xl)',
      full: 'var(--ai-radius-full)',
      base: 'var(--ai-radius-base)',
    },
    variantValues: ['none', 'sm', 'md', 'lg', 'xl', 'full'],
  },
  {
    id: 'border-radius-block-start',
    family: 'borders',
    priority: 'P1',
    tier: 'C',
    prefix: 'rounded-t',
    props: ['border-start-start-radius', 'border-start-end-radius'],
    values: { none: 'var(--ai-radius-none)', sm: 'var(--ai-radius-sm)', md: 'var(--ai-radius-md)', lg: 'var(--ai-radius-lg)', xl: 'var(--ai-radius-xl)', full: 'var(--ai-radius-full)' },
  },
  {
    id: 'border-radius-block-end',
    family: 'borders',
    priority: 'P1',
    tier: 'C',
    prefix: 'rounded-b',
    props: ['border-end-start-radius', 'border-end-end-radius'],
    values: { none: 'var(--ai-radius-none)', sm: 'var(--ai-radius-sm)', md: 'var(--ai-radius-md)', lg: 'var(--ai-radius-lg)', xl: 'var(--ai-radius-xl)', full: 'var(--ai-radius-full)' },
  },
  {
    id: 'border-radius-inline-start',
    family: 'borders',
    priority: 'P1',
    tier: 'C',
    prefix: 'rounded-s',
    props: ['border-start-start-radius', 'border-end-start-radius'],
    values: { none: 'var(--ai-radius-none)', sm: 'var(--ai-radius-sm)', md: 'var(--ai-radius-md)', lg: 'var(--ai-radius-lg)', xl: 'var(--ai-radius-xl)', full: 'var(--ai-radius-full)' },
  },
  {
    id: 'border-radius-inline-end',
    family: 'borders',
    priority: 'P1',
    tier: 'C',
    prefix: 'rounded-e',
    props: ['border-start-end-radius', 'border-end-end-radius'],
    values: { none: 'var(--ai-radius-none)', sm: 'var(--ai-radius-sm)', md: 'var(--ai-radius-md)', lg: 'var(--ai-radius-lg)', xl: 'var(--ai-radius-xl)', full: 'var(--ai-radius-full)' },
  },
  {
    id: 'ring',
    family: 'borders',
    priority: 'P1',
    tier: 'C',
    states: ['focusOnly', 'interactive'],
    prefix: null,
    props: ['box-shadow'],
    values: {
      ring: '0 0 0 var(--ai-focus-width) var(--ai-focus-color)',
      'ring-offset': 'var(--ai-focus-ring)',
      'ring-accent': '0 0 0 var(--ai-focus-width) color-mix(in srgb, var(--ai-accent) 65%, transparent)',
      'ring-danger': '0 0 0 var(--ai-focus-width) color-mix(in srgb, var(--ai-danger) 65%, transparent)',
      'ring-success': '0 0 0 var(--ai-focus-width) color-mix(in srgb, var(--ai-success) 65%, transparent)',
      'ring-none': 'none',
    },
    notes: 'ring and shadow both write box-shadow and cannot compose. Documented, not fixed: fixing it means a --ai-shadow-stack var chain on every component, which is a bigger change than this generator.',
  },
  {
    id: 'outline',
    family: 'borders',
    priority: 'P2',
    tier: 'C',
    prefix: 'outline',
    props: ['outline-style'],
    values: { none: 'none', solid: 'solid', dashed: 'dashed' },
  },

  /* ===== P1 effects ======================================================= */
  {
    id: 'box-shadow',
    family: 'effects',
    priority: 'P0',
    tier: 'C',
    states: ['interactive', 'theme'],
    prefix: 'shadow',
    props: ['box-shadow'],
    values: {
      none: 'none',
      sm: 'var(--ai-shadow-sm)',
      md: 'var(--ai-shadow-md)',
      lg: 'var(--ai-shadow-lg)',
      xl: 'var(--ai-shadow-xl)',
      inner: 'var(--ai-shadow-inner)',
    },
  },
  {
    id: 'opacity',
    family: 'effects',
    priority: 'P0',
    tier: 'C',
    states: ['interactive', 'theme', 'disabled'],
    prefix: 'opacity',
    props: ['opacity'],
    values: { 0: '0', 5: '0.05', 10: '0.1', 25: '0.25', 40: '0.4', 50: '0.5', 60: '0.6', 75: '0.75', 90: '0.9', 100: '1' },
  },
  {
    id: 'mix-blend-mode',
    family: 'effects',
    priority: 'P2',
    tier: 'C',
    prefix: 'mix-blend',
    props: ['mix-blend-mode'],
    values: { normal: 'normal', multiply: 'multiply', screen: 'screen', overlay: 'overlay', difference: 'difference', luminosity: 'luminosity' },
  },
  {
    id: 'accent-color',
    family: 'effects',
    priority: 'P2',
    tier: 'C',
    prefix: 'accent',
    props: ['accent-color'],
    values: { auto: 'auto', accent: 'var(--ai-accent)', primary: 'var(--ai-primary)' },
  },
  {
    id: 'caret-color',
    family: 'effects',
    priority: 'P2',
    tier: 'C',
    prefix: 'caret',
    props: ['caret-color'],
    values: { accent: 'var(--ai-accent)', current: 'currentColor', transparent: 'transparent' },
  },

  /* ===== P1 overflow and scroll =========================================== */
  {
    id: 'overflow',
    family: 'interaction',
    priority: 'P0',
    tier: 'B',
    prefix: 'overflow',
    props: ['overflow'],
    values: { auto: 'auto', hidden: 'hidden', visible: 'visible', scroll: 'scroll', clip: 'clip' },
    variantValues: ['auto', 'hidden', 'visible'],
  },
  {
    id: 'overflow-x',
    family: 'interaction',
    priority: 'P0',
    tier: 'C',
    prefix: 'overflow-x',
    props: ['overflow-x'],
    values: { auto: 'auto', hidden: 'hidden', visible: 'visible', scroll: 'scroll', clip: 'clip' },
  },
  {
    id: 'overflow-y',
    family: 'interaction',
    priority: 'P0',
    tier: 'C',
    prefix: 'overflow-y',
    props: ['overflow-y'],
    values: { auto: 'auto', hidden: 'hidden', visible: 'visible', scroll: 'scroll', clip: 'clip' },
  },
  {
    id: 'overscroll-behavior',
    family: 'interaction',
    priority: 'P2',
    tier: 'C',
    prefix: 'overscroll',
    props: ['overscroll-behavior'],
    values: { auto: 'auto', contain: 'contain', none: 'none' },
  },
  {
    id: 'scroll-behavior',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    prefix: 'scroll',
    props: ['scroll-behavior'],
    values: { smooth: 'smooth', auto: 'auto' },
  },
  {
    id: 'scroll-margin-top',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    prefix: 'scroll-mt',
    props: ['scroll-margin-top'],
    values: map([...SPACE_RESP, '20', '24'], spaceToken),
    notes:
      'SPACE_RESP plus 20 and 24. The old hand-written file shipped scroll-mt-20 and scroll-mt-24 and neither is on rename-map.json, so SPACE_RESP alone would have dropped two classes silently. Two extra rules on a tier C family; the sticky-header offset is exactly the case that wants the larger steps.',
  },
  {
    id: 'scroll-padding-top',
    family: 'interaction',
    priority: 'P2',
    tier: 'C',
    prefix: 'scroll-pt',
    props: ['scroll-padding-top'],
    values: map(SPACE_RESP, spaceToken),
  },
  {
    id: 'scroll-snap-type',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    prefix: 'snap',
    props: ['scroll-snap-type'],
    values: { x: 'x mandatory', y: 'y mandatory', both: 'both mandatory', proximity: 'both proximity', none: 'none' },
  },
  {
    id: 'scroll-snap-align',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    prefix: 'snap',
    props: ['scroll-snap-align'],
    values: { start: 'start', center: 'center', end: 'end' },
  },
  {
    id: 'scroll-snap-stop',
    family: 'interaction',
    priority: 'P2',
    tier: 'C',
    prefix: 'snap',
    props: ['scroll-snap-stop'],
    values: { always: 'always', normal: 'normal' },
  },

  /* ===== P1 interaction =================================================== */
  {
    id: 'cursor',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    states: ['disabled'],
    prefix: 'cursor',
    props: ['cursor'],
    values: {
      auto: 'auto', default: 'default', pointer: 'pointer', wait: 'wait', text: 'text',
      move: 'move', 'not-allowed': 'not-allowed', grab: 'grab', grabbing: 'grabbing',
      'zoom-in': 'zoom-in', 'zoom-out': 'zoom-out', help: 'help', progress: 'progress', none: 'none',
    },
  },
  {
    id: 'pointer-events',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    prefix: 'pointer-events',
    props: ['pointer-events'],
    values: { none: 'none', auto: 'auto' },
  },
  {
    id: 'user-select',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    prefix: 'user-select',
    props: ['user-select'],
    values: { none: 'none', text: 'text', all: 'all', auto: 'auto' },
    notes: 'Renamed from select-*. `select-none` read as "style a <select>", and select-* is the natural prefix if the form components ever ship select utilities.',
  },
  {
    id: 'touch-action',
    family: 'interaction',
    priority: 'P2',
    tier: 'C',
    prefix: 'touch',
    props: ['touch-action'],
    values: { auto: 'auto', none: 'none', 'pan-x': 'pan-x', 'pan-y': 'pan-y', manipulation: 'manipulation' },
  },
  {
    id: 'resize',
    family: 'interaction',
    priority: 'P2',
    tier: 'C',
    prefix: null,
    props: ['resize'],
    values: { resize: 'both', 'resize-none': 'none', 'resize-x': 'horizontal', 'resize-y': 'vertical' },
  },
  {
    id: 'appearance',
    family: 'interaction',
    priority: 'P2',
    tier: 'C',
    prefix: 'appearance',
    props: ['appearance'],
    values: { none: 'none', auto: 'auto' },
  },
  {
    id: 'will-change',
    family: 'interaction',
    priority: 'P2',
    tier: 'C',
    prefix: 'will-change',
    props: ['will-change'],
    values: { auto: 'auto', transform: 'transform', opacity: 'opacity', scroll: 'scroll-position' },
  },

  /* ===== P1 transforms and motion ========================================= */
  {
    id: 'scale',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    states: ['interactive', 'motion'],
    prefix: 'scale',
    props: ['scale'],
    values: { 0: '0', 50: '0.5', 75: '0.75', 90: '0.9', 95: '0.95', 100: '1', 105: '1.05', 110: '1.1', 125: '1.25', 150: '1.5' },
  },
  {
    id: 'rotate',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    prefix: 'rotate',
    props: ['rotate'],
    values: map([0, 1, 2, 3, 6, 12, 45, 90, 180], (n) => `${n}deg`),
  },
  {
    id: 'rotate-negative',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    prefix: '-rotate',
    props: ['rotate'],
    values: map([1, 2, 3, 6, 12, 45, 90, 180], (n) => `-${n}deg`),
  },
  {
    id: 'translate-x',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    states: ['interactive', 'motion'],
    prefix: 'translate-x',
    props: ['translate'],
    values: { ...map(['0', 'px', '1', '2', '3', '4', '6', '8', '12'], (k) => `${spaceToken(k)} 0`), full: '100% 0', half: '50% 0' },
  },
  {
    id: 'translate-y',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    states: ['interactive', 'motion'],
    prefix: 'translate-y',
    props: ['translate'],
    values: { ...map(['0', 'px', '1', '2', '3', '4', '6', '8', '12'], (k) => `0 ${spaceToken(k)}`), full: '0 100%', half: '0 50%' },
  },
  {
    id: 'translate-x-negative',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    prefix: '-translate-x',
    props: ['translate'],
    values: { ...map(['px', '1', '2', '3', '4', '6', '8', '12'], (k) => `${negSpace(k)} 0`), full: '-100% 0', half: '-50% 0' },
  },
  {
    id: 'translate-y-negative',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    prefix: '-translate-y',
    props: ['translate'],
    values: { ...map(['px', '1', '2', '3', '4', '6', '8', '12'], (k) => `0 ${negSpace(k)}`), full: '0 -100%', half: '0 -50%' },
  },
  {
    id: 'transform-origin',
    family: 'interaction',
    priority: 'P2',
    tier: 'C',
    prefix: 'origin',
    props: ['transform-origin'],
    values: {
      center: 'center', top: 'top', bottom: 'bottom', left: 'left', right: 'right',
      'top-left': 'top left', 'top-right': 'top right', 'bottom-left': 'bottom left', 'bottom-right': 'bottom right',
    },
  },
  {
    id: 'transition-property',
    family: 'interaction',
    priority: 'P0',
    tier: 'C',
    states: ['motion'],
    prefix: null,
    props: ['transition-property'],
    values: {
      transition: 'color, background-color, border-color, opacity, box-shadow, transform, translate, scale',
      'transition-none': 'none',
      'transition-colors': 'color, background-color, border-color',
      'transition-opacity': 'opacity',
      'transition-shadow': 'box-shadow',
      'transition-transform': 'transform, translate, scale, rotate',
      'transition-all': 'all',
    },
    notes:
      'Property list only. The old `.transition` wrote the full shorthand, which meant `transition duration-slow` lost to the shorthand\'s own 150ms. Duration and easing now come from their own families, with the defaults declared once in the extra sheet.',
  },
  {
    id: 'transition-duration',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    states: ['motion'],
    prefix: 'duration',
    props: ['transition-duration'],
    values: { 0: '0ms', fast: 'var(--ai-duration-fast)', normal: 'var(--ai-duration-normal)', slow: 'var(--ai-duration-slow)' },
  },
  {
    id: 'transition-timing',
    family: 'interaction',
    priority: 'P1',
    tier: 'C',
    prefix: 'ease',
    props: ['transition-timing-function'],
    values: { out: 'var(--ai-ease-out)', 'in-out': 'var(--ai-ease-in-out)', smooth: 'var(--ai-ease-smooth)', spring: 'var(--ai-ease-spring)', linear: 'linear' },
  },
  {
    id: 'transition-delay',
    family: 'interaction',
    priority: 'P2',
    tier: 'C',
    prefix: 'delay',
    props: ['transition-delay'],
    values: { 0: '0ms', 75: '75ms', 150: '150ms', 300: '300ms' },
  },

  /* ===== P1 content flow ================================================== */
  {
    id: 'object-fit',
    family: 'layout',
    priority: 'P1',
    tier: 'C',
    prefix: 'object',
    props: ['object-fit'],
    values: { contain: 'contain', cover: 'cover', fill: 'fill', none: 'none', 'scale-down': 'scale-down' },
  },
  {
    id: 'object-position',
    family: 'layout',
    priority: 'P2',
    tier: 'C',
    prefix: 'object',
    props: ['object-position'],
    values: { center: 'center', top: 'top', bottom: 'bottom', left: 'left', right: 'right' },
  },
  {
    id: 'columns',
    family: 'layout',
    priority: 'P1',
    tier: 'B',
    prefix: 'columns',
    props: ['columns'],
    values: { ...map(range(1, 6), String), auto: 'auto' },
    variantValues: ['1', '2', '3', 'auto'],
  },
  {
    id: 'break-inside',
    family: 'layout',
    priority: 'P2',
    tier: 'C',
    prefix: 'break-inside',
    props: ['break-inside'],
    values: { avoid: 'avoid', auto: 'auto', 'avoid-page': 'avoid-page' },
  },
  {
    id: 'break-before',
    family: 'layout',
    priority: 'P2',
    tier: 'C',
    prefix: 'break-before',
    props: ['break-before'],
    values: { auto: 'auto', page: 'page', avoid: 'avoid', column: 'column' },
    notes: 'Replaces print-break-before. The property already only applies in paged and multicol contexts, so a print: variant would be noise.',
  },
  {
    id: 'break-after',
    family: 'layout',
    priority: 'P2',
    tier: 'C',
    prefix: 'break-after',
    props: ['break-after'],
    values: { auto: 'auto', page: 'page', avoid: 'avoid', column: 'column' },
  },

  /* ===== group marker ===================================================== */
  {
    id: 'group',
    family: 'interaction',
    priority: 'P0',
    tier: 'C',
    prefix: null,
    props: [],
    values: { group: { '--ai-group': '1' } },
    notes:
      'Marker for the group-hover: variant. It declares a custom property rather than nothing at all so the rule survives minification and so build-manifests sees the class. The property is otherwise unread.',
  },
];

/**
 * Hand-written utilities that stay in src/css/utilities.extra.css. The
 * generator never touches that file. Listed here so --check can assert the
 * two sets do not overlap and so the docs build can label them.
 */
export const keepList = [
  { class: 'container', why: 'fluid width plus breakpoint-stepped padding; three rules, not a value map' },
  { class: 'container-sm', why: 'new Bootstrap-shaped fluid-then-capped container; a cascade of caps across five breakpoints' },
  { class: 'container-md', why: 'as container-sm' },
  { class: 'container-lg', why: 'as container-sm' },
  { class: 'container-xl', why: 'as container-sm' },
  { class: 'container-2xl', why: 'as container-sm' },
  { class: 'container-fluid', why: 'pairs with the container cascade' },
  { class: 'truncate', why: 'three unrelated declarations under one name' },
  { class: 'line-clamp-1', why: '-webkit-box stack; line-clamp-none inverts three of the four declarations' },
  { class: 'line-clamp-2', why: 'as line-clamp-1' },
  { class: 'line-clamp-3', why: 'as line-clamp-1' },
  { class: 'line-clamp-none', why: 'as line-clamp-1' },
  { class: 'sr-only', why: 'nine declarations, and not-sr-only must undo exactly those nine' },
  { class: 'not-sr-only', why: 'as sr-only' },
  { class: 'grid-auto-fit', why: 'sets display and a repeat(auto-fit, minmax(var(), 1fr)) template together' },
  { class: 'grid-min-xs', why: 'tunes --ai-grid-min for grid-auto-fit; a knob, not a property' },
  { class: 'grid-min-sm', why: 'as grid-min-xs' },
  { class: 'grid-min-md', why: 'as grid-min-xs' },
  { class: 'grid-min-lg', why: 'as grid-min-xs' },
  { class: 'translate-center', why: 'transform shorthand pairing two axes; the translate-x/-y families use the `translate` property and cannot express it' },
  { class: 'translate-x-center', why: 'as translate-center' },
  { class: 'translate-y-center', why: 'as translate-center' },
  { class: 'blur-sm', why: 'filter utilities overwrite each other; composing them needs a --ai-filter-* var chain, which is a separate piece of work' },
  { class: 'blur', why: 'as blur-sm' },
  { class: 'blur-lg', why: 'as blur-sm' },
  { class: 'blur-none', why: 'as blur-sm' },
  { class: 'grayscale', why: 'as blur-sm' },
  { class: 'grayscale-0', why: 'as blur-sm' },
  { class: 'brightness-90', why: 'as blur-sm' },
  { class: 'brightness-110', why: 'as blur-sm' },
  { class: 'contrast-more', why: 'as blur-sm' },
  { class: 'invert', why: 'as blur-sm' },
  { class: 'saturate-0', why: 'as blur-sm' },
  { class: 'saturate-150', why: 'as blur-sm' },
  { class: 'backdrop-blur-sm', why: 'needs the -webkit- pair emitted alongside the standard property' },
  { class: 'backdrop-blur', why: 'as backdrop-blur-sm' },
  { class: 'backdrop-blur-lg', why: 'as backdrop-blur-sm' },
  { class: 'backdrop-none', why: 'as backdrop-blur-sm' },
  { class: 'w-var', why: 'escape hatch reading an author-set custom property' },
  { class: 'h-var', why: 'as w-var' },
  { class: 'min-w-var', why: 'as w-var' },
  { class: 'max-w-var', why: 'as w-var' },
  { class: 'p-var', why: 'as w-var' },
  { class: 'm-var', why: 'as w-var' },
  { class: 'gap-var', why: 'as w-var' },
  { class: 'grid-cols-var', why: 'as w-var' },
  { class: 'transform-var', why: 'as w-var' },
  { class: 'bg-var', why: 'as w-var' },
  { class: 'text-var', why: 'as w-var' },
  { class: 'prose', why: 'descendant typography block; listed by the audit but not present in utilities.css today, so it is a new hand-written addition rather than a migration' },
  { class: '@media print block', why: 'hides .modal, .drawer, .toast-container, .consent-bar, .command-palette and restyles body and a[href]; element and component selectors, not utilities' },
  { class: 'transition defaults', why: 'the single rule that gives every transition-* utility its default duration and easing' },
];

export default { families, breakpoints, containerTiers, stateVariants, stateSets, tiers, tokensToAdd, tokensToAddZ, keepList };
