import '../runtime/index';
import stats from '../registry/stats.json';
import { getBrowserToken, validateToken } from './license';

const MOON = `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"></path></svg>`;
const BURGER = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M4 7h16"/><path d="M4 12h16"/><path d="M4 17h16"/></svg>`;
const CLOSE = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M6 6l12 12"/><path d="M18 6L6 18"/></svg>`;
const SUN = `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/></svg>`;

// Counts come from src/registry/stats.json, generated by build-registry.mjs.
// Importing the component array here would ship the whole registry on every
// page, so the chrome only ever sees the numbers.
export const catalogStats = stats;

function pageId(): string {
  const p = location.pathname;
  if (p.includes('components')) return 'components';
  if (p.includes('templates')) return 'templates';
  if (p.includes('quickstart')) return 'docs';
  if (p.includes('account')) return 'account';
  return 'home';
}

function navLink(href: string, id: string, label: string, cls = 'nav-link', extra = ''): string {
  const active = pageId() === id ? ' is-active' : '';
  return `<a href="${href}" class="${cls}${active}"${extra}>${label}</a>`;
}

// Preferences moved from cssai-* to llmcss-*. Read the new key, fall back to the
// old one once, and migrate it so the old key is never read again. Key names are
// llmcss-theme, llmcss-skin, llmcss-focus, llmcss-radius, llmcss-density,
// llmcss-accent and llmcss-template-mode.
export function readPref(key: string): string | null {
  try {
    const current = localStorage.getItem(`llmcss-${key}`);
    if (current !== null) return current;
    const legacy = localStorage.getItem(`cssai-${key}`);
    if (legacy !== null) localStorage.setItem(`llmcss-${key}`, legacy);
    return legacy;
  } catch {
    return null;
  }
}

export function writePref(key: string, value: string) {
  try {
    localStorage.setItem(`llmcss-${key}`, value);
  } catch {
    // storage blocked
  }
}

// The pricing modal only exists on the home page. Everywhere else the CTA has
// nothing to open, so it keeps linking straight to checkout.
function hasProModal(): boolean {
  return !!document.getElementById('pro-pricing-modal');
}

function proCtaHtml(licensed: boolean): string {
  if (licensed) {
    return `<a href="/account" class="btn btn-outline btn-sm" id="pro-cta">Licensed</a>`;
  }
  if (hasProModal()) {
    return `<button type="button" class="btn btn-primary btn-sm" id="pro-cta" data-ai-toggle="modal" data-ai-target="#pro-pricing-modal" aria-haspopup="dialog" aria-expanded="false">Get Pro · $9/mo</button>`;
  }
  return `<a href="/api/checkout.php" class="btn btn-primary btn-sm" id="pro-cta">Get Pro · $9/mo</a>`;
}

export function applyTheme(theme: 'light' | 'dark') {
  document.documentElement.setAttribute('data-ai-theme', theme);
  writePref('theme', theme);
  document.querySelectorAll('#theme-mode-toggle').forEach((btn) => {
    btn.innerHTML = theme === 'dark' ? SUN : MOON;
    btn.setAttribute('aria-label', theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode');
    btn.setAttribute('title', theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode');
  });
  document.dispatchEvent(new CustomEvent('ai-theme-change', { detail: { theme } }));
}

export function currentTheme(): 'light' | 'dark' {
  const saved = readPref('theme');
  if (saved === 'dark' || saved === 'light') return saved;
  return (document.documentElement.getAttribute('data-ai-theme') as 'light' | 'dark') || 'light';
}

const SEARCH_ICON = `<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>`;

function searchHtml(): string {
  const id = pageId();
  const field = (inputId: string, placeholder: string, label: string) =>
    `<div class="input-group">
      <span class="input-addon">${SEARCH_ICON}</span>
      <input type="search" id="${inputId}" class="input" placeholder="${placeholder}" aria-label="${label}" />
    </div>`;
  if (id === 'components') return field('catalog-search', `Search ${catalogStats.total} components`, 'Search components');
  if (id === 'templates') return field('template-search', 'Search templates', 'Search templates');
  return '';
}

function hasStyler(): boolean {
  return !!document.getElementById('core-styler-drawer');
}

function stylerBtn(id: string, extraClass = ''): string {
  if (!hasStyler()) return '';
  return `<button type="button" id="${id}" class="btn btn-outline btn-sm ${extraClass}" data-ai-toggle="drawer" data-ai-target="#core-styler-drawer">Styler</button>`;
}

const NAV: Array<[string, string, string]> = [
  ['/components.html', 'components', 'Components'],
  ['/templates.html', 'templates', 'Templates'],
  ['/quickstart', 'docs', 'Docs'],
  ['/#pricing', 'pricing', 'Pricing'],
  ['/account', 'account', 'Account'],
];

const VERSION = typeof __LLMCSS_VERSION__ === 'string' ? __LLMCSS_VERSION__ : '';
const CHANGELOG = 'https://github.com/maku-au/llmcss/blob/main/CHANGELOG.md';
// Version sits between two vertical dividers as plain mono text, not a badge.
const VERSION_BADGE = VERSION
  ? `<span class="hidden md:inline-flex items-center gap-2">
      <span class="divider-vertical"></span>
      <a href="${CHANGELOG}" class="font-mono text-xs text-muted tabular" title="Changelog">v${VERSION}</a>
    </span>`
  : '';

const BRAND = `<a href="/" class="brand">
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none"><rect x="3" y="3" width="12" height="12" rx="2.5" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><rect x="9" y="9" width="12" height="12" rx="2.5" fill="currentColor"/></svg>
      <span>LLMCSS</span>
    </a>`;

// Header: navbar from the catalog. Links and the Pro CTA show from lg;
// below that a burger opens the drawer menu. Catalog search drops to its
// own row under md.
function headerHtml(licensed: boolean): string {
  const search = searchHtml();
  return `<div class="container container-w-lg navbar-inner">
    ${BRAND}
    ${VERSION_BADGE}
    <nav class="nav-links hidden lg:flex lg:mx-auto" id="desktop-nav" aria-label="Primary">
      ${NAV.map(([href, id, label]) => navLink(href, id, label)).join('\n      ')}
    </nav>
    ${search ? `<div class="navbar-search w-full order-last md:w-auto md:order-none md:ml-auto lg:ml-0">${search}</div>` : ''}
    <div class="flex items-center gap-2 ${search ? 'ml-auto md:ml-0' : 'ml-auto lg:ml-0'}">
      ${stylerBtn('open-styler-btn', 'hidden lg:inline-flex')}
      <button type="button" id="theme-mode-toggle" class="btn btn-outline btn-sm btn-icon">${currentTheme() === 'dark' ? SUN : MOON}</button>
      <span class="hidden lg:inline-flex">${proCtaHtml(licensed)}</span>
      <button type="button" class="btn btn-outline btn-sm btn-icon lg:hidden" id="site-menu-btn" data-ai-toggle="drawer" data-ai-target="#site-menu" aria-controls="site-menu" aria-expanded="false" aria-label="Open menu">${BURGER}</button>
    </div>
  </div>`;
}

// Mobile menu: the catalog's mobile-nav-drawer component.
function menuHtml(licensed: boolean): string {
  // The menu button cannot carry data-ai-dismiss and data-ai-toggle at once:
  // the runtime handles dismiss first and returns. mountChrome closes the menu
  // and opens the modal in one handler instead.
  const buy = hasProModal()
    ? `<button type="button" id="site-menu-pro-btn" class="btn btn-primary w-full" data-ai-target="#pro-pricing-modal" aria-haspopup="dialog" aria-expanded="false">Get Pro · $9/mo</button>`
    : `<a href="/api/checkout.php" class="btn btn-primary w-full">Get Pro · $9/mo</a>`;
  const cta = licensed ? `<a href="/account" class="btn btn-outline w-full">Licensed</a>` : buy;
  const styler = hasStyler()
    ? `<button type="button" id="site-menu-styler-btn" class="btn btn-outline w-full" data-ai-toggle="drawer" data-ai-target="#core-styler-drawer">Styler</button>`
    : '';
  return `<div class="drawer-backdrop" data-ai-dismiss="drawer"></div>
    <div class="drawer-panel" role="dialog" aria-modal="true" aria-label="Menu">
      <div class="drawer-header">
        ${BRAND}
        <button type="button" class="btn btn-ghost btn-icon btn-sm" data-ai-dismiss="drawer" aria-label="Close menu">${CLOSE}</button>
      </div>
      <nav class="drawer-body drawer-nav" aria-label="Primary">
        ${NAV.map(([href, id, label]) => navLink(href, id, label, 'sidebar-item', ' data-ai-dismiss="drawer"')).join('\n        ')}
      </nav>
      <div class="drawer-footer flex gap-2">
        ${styler}
        ${cta}
      </div>
    </div>`;
}

export function footerHtml(): string {
  const s = catalogStats;
  // Columns collapse into an accordion below 768px (library footer-col pattern).
  const chevron = `<svg class="accordion-chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>`;
  // The toggle owns aria-expanded, so it also has to name the list it expands.
  const col = (title: string, items: string[]) => {
    const listId = `footer-list-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
    return `<div class="footer-col accordion-item">
          <h4 class="footer-heading"><button type="button" class="footer-col-toggle" data-ai-toggle="accordion" aria-expanded="false" aria-controls="${listId}">${title} ${chevron}</button></h4>
          <ul class="footer-list accordion-content" id="${listId}">
            ${items.map((i) => `<li>${i}</li>`).join('\n            ')}
          </ul>
        </div>`;
  };
  // No colour utility on these links: utilities outrank the components layer,
  // so text-secondary would freeze the hover state. .footer-list a owns both.
  const link = (href: string, label: string) => `<a href="${href}">${label}</a>`;
  const cmd = (href: string, label: string) => `<a href="${href}" class="footer-cmd">${label}</a>`;
  return `<div class="container container-w-lg">
      <div class="footer-grid">
        <div class="footer-brand">
          ${BRAND}
          <p class="footer-blurb">Native CSS for agents and humans. Pro themed kits are $9 a month.</p>
        </div>
        ${col('Catalog', [
          `${link('/components.html', `Components (<span data-ai-stat="total">${s.total}</span>)`)}<span class="footer-stat">Free <span data-ai-stat="free">${s.free}</span> &middot; Pro <span data-ai-stat="pro">${s.pro}</span></span>`,
          link('/templates.html', 'Templates'),
          link('/#pricing', 'Pricing'),
        ])}
        ${col('Resources', [
          link('/quickstart', 'Docs'),
          link('/account', 'Account'),
          link('/llms.txt', 'llms.txt'),
          link('https://github.com/maku-au/llmcss', 'GitHub'),
        ])}
        ${col('CLI', [
          cmd('/quickstart', 'npx llmcss add &lt;id&gt;'),
          cmd('/quickstart', 'npx llmcss-mcp'),
          `<span class="footer-stat">Add any component, or run the MCP server.</span>`,
        ])}
      </div>
      <div class="footer-bottom">
        <p>&copy; 2026 LLMCSS. Core released under the MIT License.</p>
        ${VERSION ? `<a href="${CHANGELOG}" class="font-mono tabular" title="Changelog">v${VERSION}</a>` : ''}
      </div>
  </div>`;
}

export function proOfferHtml(): string {
  // The card explains the plan; checkout lives behind the modal so nobody is
  // sent to Polar without seeing what ships today.
  const proCta = hasProModal()
    ? `<button type="button" class="btn btn-primary w-full mt-6" data-ai-toggle="modal" data-ai-target="#pro-pricing-modal" aria-haspopup="dialog" aria-expanded="false">See what is in Pro</button>`
    : `<a href="/api/checkout.php" class="btn btn-primary w-full mt-6">Get Pro · $9/mo</a>`;
  return `<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
    <div class="card p-8">
      <div class="flex justify-between items-center">
        <h3 class="card-title">Community</h3>
        <span class="badge badge-neutral">MIT</span>
      </div>
      <div class="pricing-amount">
        <span class="pricing-price">$0</span>
        <span class="pricing-period">/ forever</span>
      </div>
      <ul class="pricing-features">
        <li>Full component catalog, wireframes, skins</li>
        <li>Free registry and local MCP</li>
        <li><code class="text-xs">npx llmcss add btn-variants</code></li>
      </ul>
      <a href="/components" class="btn btn-outline w-full mt-6">Browse free components</a>
    </div>
    <div class="card card-pro p-8 shadow-md">
      <div class="flex justify-between items-center">
        <h3 class="card-title">Pro</h3>
        <span class="badge badge-solid">$9/mo</span>
      </div>
      <div class="pricing-amount">
        <span class="pricing-price">$9</span>
        <span class="pricing-period">/ month</span>
      </div>
      <ul class="pricing-features">
        <li><span data-ai-stat="themedSections">${catalogStats.themedSections}</span> themed sections and <span data-ai-stat="kits">${catalogStats.kits}</span> page kits</li>
        <li>Skinned for editorial, fintech and obsidian</li>
        <li>Token-gated registry, MCP, and zip backup</li>
      </ul>
      ${proCta}
    </div>
  </div>
  <p class="text-xs text-muted mt-8 text-center max-w-xl mx-auto">
    Digital goods. Refunds follow Polar policy. MIT core stays free. Checkout via Polar.
  </p>`;
}

// Focus ring preference: data-ai-focus="accent|neutral|thin|none" on <html>,
// persisted so it survives navigation. The head script applies it before paint.
const FOCUS_LABELS: Record<string, string> = { accent: 'Accent', neutral: 'Neutral', thin: 'Thin', none: 'Off' };

export function applyFocusPreference(value: string) {
  const v = FOCUS_LABELS[value] ? value : 'accent';
  if (v === 'accent') document.documentElement.removeAttribute('data-ai-focus');
  else document.documentElement.setAttribute('data-ai-focus', v);
  writePref('focus', v);
  document.querySelectorAll('.js-styler-focus-btn').forEach((btn) => {
    const on = btn.getAttribute('data-focus') === v;
    btn.classList.toggle('is-active', on);
    btn.setAttribute('aria-pressed', String(on));
  });
  const label = document.getElementById('styler-focus-label');
  if (label) label.textContent = FOCUS_LABELS[v];
}

function bindFocusPreference() {
  applyFocusPreference(readPref('focus') || 'accent');
  document.querySelectorAll('.js-styler-focus-btn').forEach((btn) => {
    btn.addEventListener('click', () => applyFocusPreference(btn.getAttribute('data-focus') || 'accent'));
  });
}

// Links inside a demo are demo data: a sidebar item, a footer column, a CTA.
// None of them lead anywhere on this site, so a click never navigates and
// never jumps the page to the top on href="#". Runtime toggles on anchors keep
// working because the runtime reads the click before this listener runs on
// the document and does its own work regardless of the default action.
const DEMO_SCOPE = '.demo-canvas, .template-frame, .template-assembled, .blueprint-modal-dialog, .docs-hero-dock-card';
function guardDemoLinks() {
  document.addEventListener('click', (e) => {
    const target = e.target as HTMLElement | null;
    const link = target?.closest<HTMLAnchorElement>('a[href]');
    if (!link || !link.closest(DEMO_SCOPE)) return;
    const href = link.getAttribute('href') || '';
    // The Pro unlock inside a locked preview is a real link and must work.
    if (/^https?:\/\/|^\/api\//.test(href)) return;
    e.preventDefault();
  });
}

// The Styler drawer opts out of the scroll lock so the page behind it is the
// live preview. Chart slot 1 is var(--ai-accent), so one toned bar inside the
// drawer shows an accent or skin swap recolouring a chart without needing a
// chart on the page. Library classes only. The tone sits on the fill, not on
// the track: a toned track is an 18 percent mix and reads as a rail, while the
// fill is the slot at full strength.
function mountStylerPreview() {
  const body = document.querySelector('#core-styler-drawer .drawer-body');
  if (!body || document.getElementById('styler-tone-preview')) return;
  const section = document.createElement('div');
  section.id = 'styler-tone-preview';
  section.className = 'styler-section';
  section.innerHTML = `<div class="styler-section-header">
      <span class="styler-section-title">Chart preview</span>
    </div>
    <div class="bar-track"><div class="bar-fill w-3/5" data-ai-tone="1"></div></div>
    <p class="text-xs text-muted">Chart slot 1 follows the accent</p>`;
  // Above the token export block, which is the last section in the drawer.
  const exportSection = body.querySelector('.styler-section-divided');
  if (exportSection) body.insertBefore(section, exportSection);
  else body.appendChild(section);
}

export async function mountChrome() {
  const licensed = !!getBrowserToken() && (await validateToken(getBrowserToken())).valid;

  const header = document.getElementById('site-header');
  if (header) {
    header.classList.add('navbar');
    header.innerHTML = headerHtml(licensed);
  }

  let menu = document.getElementById('site-menu');
  if (!menu) {
    menu = document.createElement('div');
    menu.id = 'site-menu';
    menu.className = 'drawer drawer-sm lg:hidden';
    header?.after(menu);
  }
  menu.innerHTML = menuHtml(licensed);

  const footer = document.getElementById('site-footer');
  if (footer) {
    footer.classList.add('footer');
    footer.innerHTML = footerHtml();
  }

  bindFocusPreference();
  guardDemoLinks();

  // Render the pricing card before hydrating, so its own data-ai-stat spans are
  // in the DOM when the pass below runs.
  const offer = document.getElementById('pro-offer');
  if (offer) offer.innerHTML = proOfferHtml();

  mountStylerPreview();

  // Catalog numbers in page copy come from the registry, never typed by hand.
  // Keys are whatever build-registry.mjs put in stats.json: total, free, pro,
  // variants, motion, the four categories, themedSections, wireframeSections,
  // kits, blueprints. total is the 122 core components; motion is the addon
  // demo count, which is deliberately not folded into total.
  document.querySelectorAll<HTMLElement>('[data-ai-stat]').forEach((el) => {
    const key = el.getAttribute('data-ai-stat') as keyof typeof catalogStats;
    if (key in catalogStats) el.textContent = String(catalogStats[key]);
  });

  applyTheme(currentTheme());

  document.getElementById('theme-mode-toggle')?.addEventListener('click', () => {
    applyTheme(currentTheme() === 'dark' ? 'light' : 'dark');
  });

  // The drawer runtime handles open, close, backdrop, and Escape. Opening the
  // Styler from inside the menu should close the menu first.
  const closeMenu = () => {
    const api = (window as any).LLMCSS;
    if (api?.close && menu) api.close(menu);
    else { menu?.classList.remove('is-open'); menu?.removeAttribute('open'); }
  };

  document.getElementById('site-menu-styler-btn')?.addEventListener('click', closeMenu);

  // Same reason: close the menu first, then open the pricing modal behind it.
  // Order matters and both calls are synchronous: closeOverlay returns focus to
  // the burger, then openOverlay moves it into .modal-box, so the modal ends up
  // holding focus. Never open first, or the close would steal it back.
  document.getElementById('site-menu-pro-btn')?.addEventListener('click', () => {
    closeMenu();
    (window as any).LLMCSS?.open?.('#pro-pricing-modal');
  });
}
